### ISSUE TITLE
Event Type extraction from PTP

### ISSUE THREAD

**Issue by MusaabKh** [SmartDataAnalytics/OpenResearch#147]
The list of event types should be extracted from the PTP data.

**Comment by WolfgangFahl** [comment]
See https://github.com/WolfgangFahl/ProceedingsTitleParser/blob/master/dictionary.yaml 

```yaml
Conference:
  type: eventType
Colloquium:
  type: eventType
Congress:
  type: eventType
Consensus Meeting:
  type: eventType
Consensus Conference:
  type: eventType
Forum:
  type: eventType
Meeting:
  type: eventType
round-table discussion:
  type: eventType
School:
  type: eventType
Seminar:
  type: eventType
Session:
  type: eventType
Summit:
  type: eventType
Symposium:
  type: eventType
Workshop:
  type: eventType
conference:
  type: eventType
congress:
  type: eventType
meeting:
  type: eventType
symposium:
  type: eventType
satellite symposium:
  type: eventType
workshop:
  type: eventType
```
