### ISSUE TITLE
Request: Add css class for formtables to MediaWiki:Common.css

### ISSUE THREAD

**Issue by tholzheim** [SmartDataAnalytics/OpenResearch#160]
Css classes I want to add:
```css
table.formtable.InfoBox {
    position:relative;
    margin: 0 0 0.5em 1em; 
    border-collapse: collapse;
    border: 1px solid #aaa;
    background: #fff;
    float: right;
    clear: right;
    width: 20em
}

table.formtable.InfoBox th:first-child {
  background: #E6F9FF;
  color: black;
  width: 20em;
  min-width: 20em;
  max-width: 20em;
  word-break: break-all;
}
```
## Intended Usage
Adding the class to wikitable holing form fields
```
{| class="formtable InfoBox mw-collapsible"
```
### Result
![formtable_with_new_css_class](https://user-images.githubusercontent.com/45004115/114158539-1334d000-9925-11eb-99ec-1d733edab9db.png)
> Tested on [orth](https://confident.dbis.rwth-aachen.de/orth/index.php?title=Special:FormEdit/Event/3DUI_2021) and [orintegrate](https://confident.dbis.rwth-aachen.de/orintegrate/index.php?title=Special:FormEdit/Event/3DUI_2021)
